[2024-06-04T15:23:43.582-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T15:23:43.603-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_sql_pipeline.first_insert_values manual__2024-06-04T20:23:36.139791+00:00 [queued]>
[2024-06-04T15:23:43.611-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_sql_pipeline.first_insert_values manual__2024-06-04T20:23:36.139791+00:00 [queued]>
[2024-06-04T15:23:43.612-0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-04T15:23:43.686-0500] {taskinstance.py:2330} INFO - Executing <Task(SqliteOperator): first_insert_values> on 2024-06-04 20:23:36.139791+00:00
[2024-06-04T15:23:43.701-0500] {standard_task_runner.py:63} INFO - Started process 15975 to run task
[2024-06-04T15:23:43.709-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'execute_sql_pipeline', 'first_insert_values', 'manual__2024-06-04T20:23:36.139791+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/execute_sql_pipeline.py', '--cfg-path', '/tmp/tmpxkrlb48i']
[2024-06-04T15:23:43.712-0500] {standard_task_runner.py:91} INFO - Job 351: Subtask first_insert_values
[2024-06-04T15:23:43.754-0500] {task_command.py:426} INFO - Running <TaskInstance: execute_sql_pipeline.first_insert_values manual__2024-06-04T20:23:36.139791+00:00 [running]> on host diallo
[2024-06-04T15:23:43.839-0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Diallo' AIRFLOW_CTX_DAG_ID='execute_sql_pipeline' AIRFLOW_CTX_TASK_ID='first_insert_values' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T20:23:36.139791+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T20:23:36.139791+00:00'
[2024-06-04T15:23:43.840-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T15:23:43.854-0500] {sql.py:276} INFO - Executing: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        
[2024-06-04T15:23:43.860-0500] {base.py:84} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-06-04T15:23:43.885-0500] {base.py:84} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-06-04T15:23:43.886-0500] {sql.py:470} INFO - Running statement: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        , parameters: None
[2024-06-04T15:23:43.887-0500] {sql.py:479} INFO - Rows affected: 5
[2024-06-04T15:23:43.951-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T15:23:43.957-0500] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=execute_sql_pipeline, task_id=first_insert_values, run_id=manual__2024-06-04T20:23:36.139791+00:00, execution_date=20240604T202336, start_date=20240604T202343, end_date=20240604T202343
[2024-06-04T15:23:44.001-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T15:23:44.021-0500] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T15:23:44.022-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
