[2024-06-04T15:39:50.816-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T15:39:50.842-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_sql_pipeline.second_insert_values manual__2024-06-04T20:39:41.619447+00:00 [queued]>
[2024-06-04T15:39:50.851-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_sql_pipeline.second_insert_values manual__2024-06-04T20:39:41.619447+00:00 [queued]>
[2024-06-04T15:39:50.851-0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-04T15:39:50.870-0500] {taskinstance.py:2330} INFO - Executing <Task(SqliteOperator): second_insert_values> on 2024-06-04 20:39:41.619447+00:00
[2024-06-04T15:39:50.874-0500] {standard_task_runner.py:63} INFO - Started process 17058 to run task
[2024-06-04T15:39:50.877-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'execute_sql_pipeline', 'second_insert_values', 'manual__2024-06-04T20:39:41.619447+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/execute_sql_pipeline.py', '--cfg-path', '/tmp/tmpmkjmxaq3']
[2024-06-04T15:39:50.879-0500] {standard_task_runner.py:91} INFO - Job 356: Subtask second_insert_values
[2024-06-04T15:39:50.919-0500] {task_command.py:426} INFO - Running <TaskInstance: execute_sql_pipeline.second_insert_values manual__2024-06-04T20:39:41.619447+00:00 [running]> on host diallo
[2024-06-04T15:39:50.993-0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Diallo' AIRFLOW_CTX_DAG_ID='execute_sql_pipeline' AIRFLOW_CTX_TASK_ID='second_insert_values' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T20:39:41.619447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T20:39:41.619447+00:00'
[2024-06-04T15:39:50.994-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T15:39:51.007-0500] {sql.py:276} INFO - Executing: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        
[2024-06-04T15:39:51.012-0500] {base.py:84} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-06-04T15:39:51.038-0500] {base.py:84} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-06-04T15:39:51.039-0500] {sql.py:470} INFO - Running statement: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        , parameters: None
[2024-06-04T15:39:51.039-0500] {sql.py:479} INFO - Rows affected: 4
[2024-06-04T15:39:51.048-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T15:39:51.052-0500] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=execute_sql_pipeline, task_id=second_insert_values, run_id=manual__2024-06-04T20:39:41.619447+00:00, execution_date=20240604T203941, start_date=20240604T203950, end_date=20240604T203951
[2024-06-04T15:39:51.089-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T15:39:51.107-0500] {logging_mixin.py:188} WARNING - /home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-06-04T15:39:51.125-0500] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-04T15:39:51.135-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
